### ISSUE TITLE
SSL timeout with kinetic-py for ASync client

### ISSUE THREAD

**Issue by nehajs** [Seagate/kinetic-py#33]
I am unable to do any async operations on SSL as Client timeouts while connecting (issue : https://github.com/Seagate/kinetic-py/issues/32) . I tried using SecureClient but it doesn't support Async operations. 

>>> from kinetic import *
>>> c=SecureClient('172.20.1.31')
>>> c.put('k1','v1')
>>> c.putAsync('k2','v2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SecureClient' object has no attribute 'putAsync'
>>>

How can be the async operations be ran with SSL in kinetic-py?
Is SecureClient going to support Async operations?

Thanks,
Neha

**Comment by icorderi** [comment]
@nehajs that's correct, the SecureClient doesn't support Async operations. Eventlet green sockets stopped working with python >= 2.7.9 ([eventlet#221](https://github.com/eventlet/eventlet/issues/221)) so when I coded SecureClient I left it as blocking only until the Eventlet issue is resolved.

You can drop to python 2.7.8 if you really want to do puts over SSL.
